apiVersion: apps/v1
kind: Deployment
metadata:
  name: 123bookalbum
  labels:
    app: 123bookalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 123bookalbum
  template:
    metadata:
      labels:
        app: 123bookalbum
    spec:
      containers:
      - name: 123bookalbum
        image: suryakasal/dcbookalbum:latest
        ports:
        - containerPort: 80
