apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbum123
  name: bookalbum123
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbum123

