apiVersion: v1
kind: Service
metadata:
  labels:
    app: 123bookalbum
  name: 123bookalbum
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: 123bookalbum

