apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum123
  labels:
    app: bookalbum123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum123
  template:
    metadata:
      labels:
        app: bookalbum123
    spec:
      containers:
      - name: bookalbum123
        image: suryakasal/dcbookalbum:latest
        ports:
        - containerPort: 80
